services:
  # frontend service
  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    image: mayl_frontend
    container_name: mayl_frontend
    ports:
      - 3002:3002
    volumes:
      - ./frontend:/frontend
      - ./frontend/.env:/frontend/.env
      - ./frontend/public:/frontend/public
    
    restart: only_when_stopped
  
  # backend service
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mayl_backend
    container_name: mayl_backend
    volumes:
      - ./backend/.env:/backend/.env
      - ./backend:/backend/
    restart: always
    ports:
      - 12000:12000

  # data base -- postgresql
  database:
    image: postgres
    container_name: mayl_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mayl_db

  # MTA (Haraka)
  haraka:
    image: instrumentisto/haraka
    container_name: mayl_mta_haraka
    ports:
      - 25:25
      - 587:587
    environment:
      HARAKA_INSTALL_PLUGINS: haraka-plugin-rcpt-postgresql,haraka-plugin-auth-enc-file@1.0
    restart: always
    volumes:
      - ./backend/src/harakaConfig/smtp.ini:/etc/haraka/config/smtp.ini
      - ./backend/src/harakaConfig/host_list.ini:/etc/haraka/config/host_list.ini
      - ./backend/src/harakConfig/outbound.ini:/etc/haraka/config/outbound.ini
      