services:
  # frontend service
  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    image: mayl_frontend
    container_name: mayl_frontend
    ports:
      - 3002:3002
    volumes:
      - ./frontend:/frontend
      - ./frontend/.env:/frontend/.env
      - ./frontend/public:/frontend/public
    
    restart: always
  
  # backend service
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mayl_backend
    container_name: mayl_backend
    volumes:
      - ./backend/.env:/backend/.env
      - ./backend:/backend/
    restart: always
    ports:
      - 12000:12000

  # data base -- postgresql
  database:
    image: postgres
    container_name: mayl_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mayl_db

  # haraka MTA.
  custom_haraka:
    build:
      context: .
      dockerfile: ./backend/src/harakaConfig/Dockerfile
    image: custom_haraka_smtp
    container_name: custom_haraka_smtp
    volumes:
      - ./backend/src/harakaConfig/relay_dest_domains.ini:/haraka_home/haraka/config/relay_dest_domains.ini
      - ./backend/src/harakaConfig/smtp.ini:/haraka_home/haraka/config/smtp.ini
      - ./backend/src/harakaConfig/host_list:/haraka_home/haraka/config/host_list
      - ./backend/src/harakaConfig/outbound.ini:/haraka_home/haraka/config/outbound.ini
      - ./backend/src/harakaConfig/relay.ini:/haraka_home/haraka/config/relay.ini
      - ./backend/src/harakaConfig/tls.ini:/haraka_home/haraka/config/tls.ini #tls configs
      - ./backend/src/harakaConfig/tls:/haraka_home/haraka/config/tls #certs folder
      - ./backend/src/harakaConfig/auth_flat_file.ini:/haraka_home/haraka/config/auth_flat_file.ini
      - ./backend/src/harakaConfig/smtp_forward.ini:/haraka_home/haraka/config/smtp_forward.ini
    ports:
      - 25:25
      - 587:587
  # nginx web server
  web_server:
    image: nginx
    container_name: web_server
    restart: always
    ports:
      - 80:80
      - 8000:8000
      - 443:443
    volumes:
      - ./backend/src/nginxConfig/nginx.conf:/etc/ngnix/conf.d/ngnix.conf

  # ubuntu container to install swaks
  ubuntu:
    image: ubuntu:latest
    container_name: swaks_container